### ISSUE TITLE
There is no code here ?

### ISSUE THREAD

**Issue by anirudhagupta** [SukeyByte/ColorFulProcessBar#1]
I search, I search on almighty Github,

This is the only repository I got, 

Look @SukeyByte  what I got, a blank repos.

**Comment by SukeyByte** [comment]
I m sorry I forgot update code.If u need i will update days later



发自我的小米手机
在 Anirudha Gupta <notifications@github.com>，2018年12月20日 下午5:59写道：

I search, I search on almightly Github,

This is the only repository I got,

Look @SukeyByte<https://github.com/SukeyByte> what I got, a blank repos.

**Comment by anirudhagupta** [comment]
@SukeyByte Thanks
